// RaceHub v5.6.2 — Phone Test Batch 1 corrections
const RH_FINAL_STORE='RaceHub_Studio_Final_v5_6';
const RH_BUILD_VERSION='5.6.2';
let rhMoreMode='stats', rhRecordsMode='records', rhFestivalMode='browse', rhSetup=null, rhHelpKey=null;
const RH_HELP={
 home:['RaceHub HQ','This is your RaceHub home. Festival creates Championships from cars in this RaceHub; Events holds racing you create; Garage, Records and Stats all belong to the selected RaceHub Space.'],
 festival:['Festival','RaceHub Championships are generated from the cars in this Space. Choose a Championship, set its Rounds and entries, then start. Entries and Rounds are frozen for that run.'],
 events:['Events','Create your own racing programme here. Events are separate from Festival Championships and stay inside the selected RaceHub Space.'],
 garage:['Garage','Your Garage belongs to this RaceHub Space. Add or correct cars here. Existing Garage data is preserved when upgrading RaceHub.'],
 records:['Records','Records are grouped by the run that created them. A Championship Record belongs to that frozen run; All-Time RaceHub Records compare results across this Space.'],
 stats:['Stats','Stats are calculated only from the currently selected RaceHub Space. Other Spaces keep their own racing history separate.'],
 settings:['Settings','Manage celebrations, Favourite Manufacturer, RaceHub Spaces and backups here. Reset Racing Data affects this Space only and keeps its Garage.']
};
function rhId(prefix='id'){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function rhClone(v){return JSON.parse(JSON.stringify(v))}
function rhSpaceTemplate(name='My RaceHub',cars=[]){return {id:rhId('space'),name,cars:cars.map(normaliseCar),favouriteManufacturer:'',runs:[],customEvents:[],backups:[],createdAt:new Date().toISOString()}}
function rhMigrateLegacy(raw){
 const cars=Array.isArray(raw?.cars)?raw.cars.map(normaliseCar):[];
 const space=rhSpaceTemplate('My RaceHub',cars);
 // Preserve old results as legacy history; new frozen-run model starts clean by design.
 space.legacyResults=Array.isArray(raw?.results)?rhClone(raw.results):[];
 return {schema:2,version:RH_BUILD_VERSION,driverName:'Driver',spaces:[space],activeSpaceId:space.id,settings:Object.assign({sound:true,confetti:true,vibrate:true},raw?.settings||{}),onboarded:true};
}
function rhLoad(){
 try{const x=JSON.parse(localStorage.getItem(RH_FINAL_STORE)||'null');if(x?.schema===2&&Array.isArray(x.spaces)&&x.spaces.length)return x;}catch(e){}
 try{const old=JSON.parse(localStorage.getItem(STORE)||'null');if(old?.cars){const x=rhMigrateLegacy(old);localStorage.setItem(RH_FINAL_STORE,JSON.stringify(x));return x;}}catch(e){}
 const x=rhMigrateLegacy({cars:Array.isArray(SEED?.cars)?SEED.cars:[],settings:{sound:true,confetti:true,vibrate:true}});localStorage.setItem(RH_FINAL_STORE,JSON.stringify(x));return x;
}
function rhSave(){localStorage.setItem(RH_FINAL_STORE,JSON.stringify(state))}
function rhSpace(){return state.spaces.find(s=>s.id===state.activeSpaceId)||state.spaces[0]}
function rhSync(){const s=rhSpace();state.cars=s.cars;state.settings=state.settings||{sound:true,confetti:true,vibrate:true};}
function save(){rhSync();const s=rhSpace();s.cars=state.cars;rhSave()}
function rhShow(screen){currentScreen=screen;rhSync();document.body.dataset.screen=screen;document.querySelectorAll('.screen').forEach(s=>s.classList.add('hidden'));$(screen).classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===screen));rhRender(screen);window.scrollTo(0,0)}
function show(screen){rhShow(screen)}
function rhHeader(title,sub,key,back='home'){return `<div class="rhPageHead"><button class="rhBack" onclick="show('${back}')">‹</button><div><h1>${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</div><button class="rhHelp" onclick="rhOpenHelp('${key}')">?</button></div>`}
function rhOpenHelp(key){rhHelpKey=key;const h=RH_HELP[key]||['RaceHub Help','Contextual help for this screen.'];document.body.insertAdjacentHTML('beforeend',`<div id="rhHelpOverlay" class="rhOverlay" onclick="if(event.target===this)rhCloseHelp()"><div class="rhModal"><button class="rhModalX" onclick="rhCloseHelp()">×</button><div class="rhQuestion">?</div><h2>${esc(h[0])}</h2><p>${esc(h[1])}</p><button class="btn" onclick="rhCloseHelp()">Got it</button></div></div>`)}
function rhCloseHelp(){document.getElementById('rhHelpOverlay')?.remove()}
function rhEmpty(title,copy,action='',fn=''){return `<div class="rhEmpty"><div class="rhEmptyMark">◇</div><h2>${esc(title)}</h2><p>${esc(copy)}</p>${action?`<button class="btn" onclick="${fn}">${esc(action)}</button>`:''}</div>`}
function rhCurrentRuns(){return rhSpace().runs||[]}
function rhActiveRun(){return rhCurrentRuns().find(r=>r.status==='active')||null}
function rhRunProgress(r){const total=(r.entries?.length||0)*(r.rounds?.length||0),done=(r.results||[]).length;return {done,total,pct:total?Math.round(done/total*100):0}}
function rhMakeList(){return [...new Set(rhSpace().cars.map(c=>c.make).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function rhEraList(){return [...new Set(rhSpace().cars.map(c=>Math.floor(Number(c.year)/10)*10).filter(y=>y>=1900&&y<=2030))].sort((a,b)=>a-b)}
function rhEligible(type,value){const cars=rhSpace().cars;if(type==='festival')return cars;if(type==='make'||type==='favourite')return cars.filter(c=>c.make===value);if(type==='era')return cars.filter(c=>Math.floor(Number(c.year)/10)*10===Number(value));return cars}
function rhTrophy(type){return `assets/final/trophy-${type}.png`}
function rhRenderHome(){const s=rhSpace(),run=rhActiveRun(),p=run?rhRunProgress(run):null;$('home').innerHTML=`<div class="rhHome"><div class="rhHomeHero"><div class="rhHomeTop"><div><small>WELCOME TO</small><b>${esc(s.name)}</b></div><button onclick="rhMoreMode='settings';show('more')">⚙</button></div><img src="assets/final/racehub-logo.png" alt="RaceHub"><button class="rhHomeHelp" onclick="rhOpenHelp('home')">?</button></div><div class="rhHomeBody">${run?`<button class="rhContinue" onclick="rhOpenRun('${run.id}')"><span>CHAMPIONSHIP IN PROGRESS</span><b>${esc(run.name)}</b><small>${p.done} of ${p.total} results recorded</small><em>${p.pct}%</em></button>`:''}<div class="rhTiles"><button onclick="show('festival')"><i>🏁</i><b>FESTIVAL</b><small>RaceHub Championships</small></button><button onclick="show('events')"><i>▣</i><b>EVENTS</b><small>Your Racing</small></button><button onclick="show('garage')"><i>⌂</i><b>GARAGE</b><small>Your Cars</small></button><button onclick="rhRecordsMode='records';show('hall')"><i>🏆</i><b>RECORDS</b><small>Records & Hall of Fame</small></button><button onclick="rhMoreMode='stats';show('more')"><i>◴</i><b>STATS</b><small>Your RaceHub</small></button></div></div></div>`}
function rhChampCard(type,value,name,count){const trophy=type==='make'?rhTrophy('manufacturer'):type==='era'?rhTrophy('era'):type==='favourite'?rhTrophy('favourite'):rhTrophy('festival');return `<button class="rhChampCard" onclick="rhBeginSetup('${type}','${esc(String(value)).replace(/'/g,'&#39;')}','${esc(name).replace(/'/g,'&#39;')}')"><img src="${trophy}"><span><b>${esc(name)}</b><small>${count} eligible car${count===1?'':'s'}</small></span><em>›</em></button>`}
function rhRenderFestival(){const s=rhSpace(),active=rhActiveRun(),makes=rhMakeList(),eras=rhEraList(),fav=s.favouriteManufacturer;$('festival').innerHTML=`<div class="rhScene rhFestivalScene">${rhHeader('FESTIVAL','RaceHub Championships','festival')}</div><div class="rhContent">${active?`<button class="rhRunBanner" onclick="rhOpenRun('${active.id}')"><span>CONTINUE RACING</span><b>${esc(active.name)}</b><small>${rhRunProgress(active).done} / ${rhRunProgress(active).total} results</small></button>`:''}<section class="rhSection"><h2>RaceHub Championships</h2>${rhChampCard('festival','all','Festival Championship',s.cars.length)}</section><section class="rhSection rhPurple"><h2>Favourite Manufacturer</h2>${fav?rhChampCard('favourite',fav,`${fav} Championship`,rhEligible('favourite',fav).length):`<div class="rhFavouriteUnset"><p>Choose a Favourite Manufacturer in Settings to unlock its Championship.</p><button class="btn secondary" onclick="rhMoreMode='settings';show('more')">SET FAVOURITE MANUFACTURER</button></div>`}</section><details class="rhSection"><summary>Era Championships <span>${eras.length}</span></summary>${eras.map(e=>rhChampCard('era',e,`${e}s Championship`,rhEligible('era',e).length)).join('')||'<p class="small">Add cars with years to unlock Era Championships.</p>'}</details><details class="rhSection"><summary>Manufacturer Championships <span>${makes.length}</span></summary><input class="rhSearch" placeholder="Search manufacturers" oninput="document.querySelectorAll('.rhMakeChamp').forEach(x=>x.hidden=!x.dataset.name.includes(this.value.toLowerCase()))">${makes.map(m=>`<div class="rhMakeChamp" data-name="${esc(m.toLowerCase())}">${rhChampCard('make',m,`${m} Championship`,rhEligible('make',m).length)}</div>`).join('')}</details></div>`}
function rhBeginSetup(type,value,name){const cars=rhEligible(type,value);rhSetup={type,value,name,entries:cars.map(c=>c.id),rounds:[{id:rhId('round'),name:'Round 1'}]};rhRenderSetup()}
function rhRenderSetup(){const x=rhSetup;if(!x)return;const cars=rhEligible(x.type,x.value);$('festival').innerHTML=`<div class="rhScene rhChampScene">${rhHeader('CHAMPIONSHIP SETUP',x.name,'festival','festival')}</div><div class="rhContent"><section class="rhSection"><div class="rhSectionTop"><div><h2>Eligible Cars</h2><p>All cars are included by default. Excluding a car affects this run only.</p></div><b class="rhSelectedCount">${x.entries.length} / ${cars.length}</b></div><div class="rhEntryTools"><input id="rhEntrySearch" class="rhSearch" placeholder="Search eligible cars" oninput="rhFilterSetupCars(this.value)"><button class="chip" onclick="rhSetAllEntries(true)">All</button><button class="chip" onclick="rhSetAllEntries(false)">None</button></div><div id="rhSetupCars" class="rhSetupCars">${cars.map(c=>`<label class="rhCheck" data-name="${esc(carName(c).toLowerCase())}"><input type="checkbox" ${x.entries.includes(c.id)?'checked':''} onchange="rhToggleEntry('${c.id}',this.checked)"><span>${esc(carName(c))}</span></label>`).join('')||'<div class="empty">No eligible cars.</div>'}</div></section><section class="rhSection"><div class="rhSectionTop"><div><h2>Rounds</h2><p>Create, rename and order the Rounds for this run.</p></div><button class="chip" onclick="rhAddRound()">＋ Add</button></div>${x.rounds.map((r,i)=>`<div class="rhRound"><b>${i+1}</b><input value="${esc(r.name)}" onchange="rhRenameRound('${r.id}',this.value)"><button onclick="rhMoveRound(${i},-1)">↑</button><button onclick="rhMoveRound(${i},1)">↓</button><button onclick="rhRemoveRound('${r.id}')">×</button></div>`).join('')}</section><button class="btn rhStart" ${!x.entries.length||!x.rounds.length?'disabled':''} onclick="rhConfirmStart()">START CHAMPIONSHIP</button><p class="rhSafeguard">Starting freezes the selected cars and Rounds for this run.</p></div>`}
function rhFilterSetupCars(q=''){q=q.toLowerCase().trim();document.querySelectorAll('#rhSetupCars .rhCheck').forEach(x=>x.hidden=!!q&&!x.dataset.name.includes(q))}
function rhSetAllEntries(on){const cars=rhEligible(rhSetup.type,rhSetup.value);rhSetup.entries=on?cars.map(c=>c.id):[];rhRenderSetup()}
function rhToggleEntry(id,on){if(on&&!rhSetup.entries.includes(id))rhSetup.entries.push(id);if(!on)rhSetup.entries=rhSetup.entries.filter(x=>x!==id)}
function rhAddRound(){rhSetup.rounds.push({id:rhId('round'),name:`Round ${rhSetup.rounds.length+1}`});rhRenderSetup()}
function rhRenameRound(id,v){const r=rhSetup.rounds.find(r=>r.id===id);if(r)r.name=v.trim()||'Untitled Round'}
function rhRemoveRound(id){rhSetup.rounds=rhSetup.rounds.filter(r=>r.id!==id);rhRenderSetup()}
function rhMoveRound(i,d){const j=i+d;if(j<0||j>=rhSetup.rounds.length)return;[rhSetup.rounds[i],rhSetup.rounds[j]]=[rhSetup.rounds[j],rhSetup.rounds[i]];rhRenderSetup()}
function rhConfirmStart(){const x=rhSetup;if(!x)return;const s=rhSpace();const run={id:rhId('run'),name:x.name,type:x.type,value:x.value,trophy:x.type==='make'?'manufacturer':x.type==='era'?'era':x.type==='favourite'?'favourite':'festival',createdAt:new Date().toISOString(),status:'active',entries:[...x.entries],rounds:rhClone(x.rounds),results:[]};s.runs.push(run);rhSave();rhSetup=null;rhOpenRun(run.id)}
function rhOpenRun(id){const r=rhCurrentRuns().find(x=>x.id===id);if(!r)return;show('festival');const p=rhRunProgress(r),next=rhNextSlot(r);$('festival').innerHTML=`<div class="rhScene rhChampScene">${rhHeader('CHAMPIONSHIP',r.name,'festival','festival')}</div><div class="rhContent"><section class="rhRunOverview"><img src="${rhTrophy(r.trophy)}"><div><span>${r.status==='complete'?'CHAMPIONSHIP COMPLETE':'CURRENT RUN'}</span><h2>${esc(r.name)}</h2><p>Created ${new Date(r.createdAt).toLocaleDateString('en-GB')}</p></div></section><section class="rhSection"><div class="rhProgressTop"><b>Progress</b><span>${p.done} / ${p.total}</span></div><div class="progress"><div class="bar" style="width:${p.pct}%"></div></div></section>${r.status==='active'&&next?`<section class="rhSection"><h2>Race Night</h2><div class="rhNext"><span>NEXT</span><b>${esc(carName(carById(next.carId)))}</b><small>${esc(next.round.name)}</small></div><button class="btn" onclick="rhEnterResult('${r.id}','${next.carId}','${next.round.id}')">CONTINUE</button><button class="btn secondary" onclick="rhShuffleQueue('${r.id}')">Shuffle Queue</button></section>`:''}<section class="rhSection"><h2>Frozen Entry List</h2>${r.entries.map(id=>`<div class="rhListRow">${esc(carName(carById(id)||{make:'Unknown',model:'Car'}))}</div>`).join('')}</section><section class="rhSection"><h2>Rounds</h2>${r.rounds.map((x,i)=>`<div class="rhListRow"><b>${i+1}</b><span>${esc(x.name)}</span></div>`).join('')}</section>${r.status==='complete'?rhLeaderboard(r):''}</div>`}
function rhNextSlot(r){for(const carId of r.entries){for(const round of r.rounds){if(!r.results.some(x=>x.carId===carId&&x.roundId===round.id))return {carId,round}}}return null}
function rhShuffleQueue(id){const r=rhCurrentRuns().find(x=>x.id===id);if(!r)return;const remaining=r.entries.filter(cid=>r.rounds.some(rd=>!r.results.some(x=>x.carId===cid&&x.roundId===rd.id)));for(let i=remaining.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[remaining[i],remaining[j]]=[remaining[j],remaining[i]]}r.entries=[...r.entries.filter(cid=>!remaining.includes(cid)),...remaining];rhSave();toast('Queue shuffled');rhOpenRun(id)}
function rhEnterResult(runId,carId,roundId){const r=rhCurrentRuns().find(x=>x.id===runId),c=carById(carId),rd=r?.rounds.find(x=>x.id===roundId);if(!r||!c||!rd)return;$('festival').innerHTML=`<div class="rhScene rhChampScene">${rhHeader('ENTER RESULT',rd.name,'festival','festival')}</div><div class="rhContent"><section class="rhSection rhResultEntry"><span>${esc(r.name)}</span><h2>${esc(carName(c))}</h2><label>TIME</label><input id="rhTime" class="rhStopwatch" inputmode="numeric" maxlength="9" placeholder="00:00.000"><label>POSITION</label><select id="rhPos"><option value="">—</option>${[1,2,3,4,5,6,7,8,9,10].map(n=>`<option>${n}</option>`).join('')}</select><button class="btn" onclick="rhSaveResult('${runId}','${carId}','${roundId}')">SAVE RESULT</button></section></div>`}
function rhParseTime(v){v=String(v||'').trim();const m=v.match(/^(\d{1,2}):([0-5]?\d)\.(\d{1,3})$/);if(m)return Number(m[1])*60+Number(m[2])+Number(('0.'+m[3].padEnd(3,'0')));const d=v.replace(/\D/g,'');if(d.length>=4){const ms=d.slice(-3),sec=d.slice(-5,-3)||'0',min=d.slice(0,-5)||'0';return Number(min)*60+Number(sec)+Number(ms)/1000}return NaN}
function rhFmtTime(v){const m=Math.floor(v/60),s=(v-m*60).toFixed(3).padStart(6,'0');return `${String(m).padStart(2,'0')}:${s}`}
function rhSaveResult(runId,carId,roundId){const r=rhCurrentRuns().find(x=>x.id===runId),v=rhParseTime($('rhTime')?.value),pos=Number($('rhPos')?.value)||null;if(!r||!isFinite(v)||v<=0){toast('Enter a valid time');return}const priorAll=rhCurrentRuns().flatMap(x=>x.results||[]).filter(x=>x.roundName===r.rounds.find(q=>q.id===roundId)?.name);const runPrior=r.results.filter(x=>x.roundId===roundId);const championshipRecord=!runPrior.length||v<Math.min(...runPrior.map(x=>x.time));const allTime=!priorAll.length||v<Math.min(...priorAll.map(x=>x.time));r.results.push({id:rhId('result'),carId,roundId,roundName:r.rounds.find(x=>x.id===roundId).name,time:v,position:pos,date:new Date().toISOString(),championshipRecord,allTime});if(!rhNextSlot(r)){r.status='complete';r.completedAt=new Date().toISOString()}rhSave();rhResultSummary(r,r.results.at(-1))}
function rhResultSummary(r,res){const c=carById(res.carId);$('festival').innerHTML=`<div class="rhScene rhChampScene">${rhHeader('RESULT SAVED',res.roundName,'festival','festival')}</div><div class="rhContent"><section class="rhClipboard"><span>OFFICIAL RESULT</span><h2>${esc(carName(c))}</h2><strong>${rhFmtTime(res.time)}</strong>${res.position?`<p>Position ${res.position}</p>`:''}<div class="rhRosettes">${res.championshipRecord?'<b>✹ Championship Record</b>':''}${res.allTime?'<b class="gold">✹ All-Time RH Record</b>':''}</div>${(res.championshipRecord||res.allTime)?'<img class="rhHubs" src="assets/final/hubs.png" alt="Hubs celebrating">':''}<button class="btn" onclick="rhOpenRun('${r.id}')">${r.status==='complete'?'FINAL LEADERBOARD':'CONTINUE'}</button></section></div>`}
function rhLeaderboard(r){const rows=r.entries.map(id=>{const rr=r.results.filter(x=>x.carId===id);return rr.length===r.rounds.length?{id,total:rr.reduce((a,b)=>a+b.time,0)}:null}).filter(Boolean).sort((a,b)=>a.total-b.total);return `<section class="rhSection"><h2>Final Leaderboard</h2>${rows.map((x,i)=>`<div class="rhLeaderRow"><b>${i+1}</b><span>${esc(carName(carById(x.id)))}</span><strong>${rhFmtTime(x.total)}</strong></div>`).join('')}</section>`}
function rhRenderEvents(){const s=rhSpace(),active=s.customEvents.filter(e=>e.status!=='complete'),done=s.customEvents.filter(e=>e.status==='complete'),hasEvents=[...active,...done].length;$('events').innerHTML=`<div class="rhScene rhEventsScene">${rhHeader('EVENTS','Your Racing','events')}</div><div class="rhContent">${hasEvents?`<button class="btn" onclick="rhCreateEvent()">CREATE EVENT</button>`:''}${active.length?`<section class="rhSection"><h2>In Progress</h2>${active.map(rhEventCard).join('')}</section>`:''}<section class="rhSection"><h2>Your Events</h2>${hasEvents?[...active,...done].map(rhEventCard).join(''):rhEmpty('NO EVENTS YET','Create an Event to build your own racing programme.','Create Event','rhCreateEvent()')}</section></div>`}
function rhEventCard(e){return `<button class="rhEventCard" onclick="rhOpenEvent('${e.id}')"><span><b>${esc(e.name)}</b><small>${e.rounds.length} round${e.rounds.length===1?'':'s'} • ${e.status==='complete'?'Completed':'Active'}</small></span><em>›</em></button>`}
function rhCreateEvent(){const name=prompt('Event name');if(!name?.trim())return;const e={id:rhId('event'),name:name.trim(),status:'active',rounds:[{id:rhId('round'),name:'Round 1'}],results:[],createdAt:new Date().toISOString()};rhSpace().customEvents.push(e);rhSave();rhOpenEvent(e.id)}
function rhOpenEvent(id){const e=rhSpace().customEvents.find(x=>x.id===id);if(!e)return;show('events');$('events').innerHTML=`<div class="rhScene rhEventsScene">${rhHeader('EVENT',e.name,'events','events')}</div><div class="rhContent"><section class="rhSection"><h2>${esc(e.name)}</h2><p>Your created racing programme.</p>${e.rounds.map((r,i)=>`<div class="rhRound"><b>${i+1}</b><input value="${esc(r.name)}" onchange="r=this.closest('.rhRound');rhRenameEventRound('${e.id}','${r.id}',this.value)"></div>`).join('')}<button class="btn secondary" onclick="rhAddEventRound('${e.id}')">＋ ADD ROUND</button></section><section class="rhSection"><h2>Results</h2>${e.results.length?e.results.map(x=>`<div class="rhListRow"><span>${esc(x.roundName)}</span><strong>${rhFmtTime(x.time)}</strong></div>`).join(''):'<div class="empty">No results recorded yet.</div>'}<button class="btn" onclick="rhEventResult('${e.id}')">ENTER RESULT</button></section></div>`}
function rhRenameEventRound(eid,rid,v){const e=rhSpace().customEvents.find(x=>x.id===eid),r=e?.rounds.find(x=>x.id===rid);if(r){r.name=v.trim()||'Untitled Round';rhSave()}}
function rhAddEventRound(id){const e=rhSpace().customEvents.find(x=>x.id===id);if(e){e.rounds.push({id:rhId('round'),name:`Round ${e.rounds.length+1}`});rhSave();rhOpenEvent(id)}}
function rhEventResult(id){const e=rhSpace().customEvents.find(x=>x.id===id);if(!e)return;const round=e.rounds[0];const raw=prompt(`Time for ${round.name} (00:00.000)`);const v=rhParseTime(raw);if(!isFinite(v))return toast('Invalid time');e.results.push({id:rhId('result'),roundId:round.id,roundName:round.name,time:v,date:new Date().toISOString()});rhSave();rhOpenEvent(id)}
function rhRenderGarage(){const s=rhSpace();garageMake=garageMake||'All';garageSearch=garageSearch||'';const makes=['All',...rhMakeList()],list=s.cars.filter(c=>(garageMake==='All'||c.make===garageMake)&&(!garageSearch||carName(c).toLowerCase().includes(garageSearch.toLowerCase())));$('garage').innerHTML=`${rhHeader('GARAGE','Your Cars','garage')}<div class="rhContent"><section class="rhSection"><div class="rhGarageCount"><b>${s.cars.length}</b><span>cars in ${esc(s.name)}</span></div><div class="rhGarageTools"><input id="garageSearch" placeholder="Search make, model or year" value="${esc(garageSearch)}"><button class="chip" onclick="garageSearch=$('garageSearch').value;rhRenderGarage()">Search</button><button class="chip" onclick="rhAddCarFinal()">＋ Add Car</button></div><div class="chips">${makes.map(m=>`<button class="chip ${m===garageMake?'on':''}" onclick="garageMake='${esc(m).replace(/'/g,'&#39;')}';rhRenderGarage()">${esc(m)}</button>`).join('')}</div>${list.length?list.map(c=>`<div class="rhCar"><span><b>${esc(c.make)}</b><strong>${esc(c.model)}</strong><small>${esc(c.year||'')}</small></span><button class="chip" onclick="editCar('${c.id}')">Edit</button></div>`).join(''):rhEmpty('YOUR GARAGE IS EMPTY','Add cars to start building Championships and recording your racing.','Add Your First Car','rhAddCarFinal()')}</section></div>`}
function rhAddCarFinal(){const make=prompt('Manufacturer');if(!make?.trim())return;const model=prompt('Model');if(!model?.trim())return;const year=prompt('Year (optional)')||'';const c=normaliseCar({id:rhId('car'),make:make.trim(),model:model.trim(),year:year.trim()});rhSpace().cars.push(c);rhSync();rhSave();rhRenderGarage()}
function rhRenderRecords(){const runs=rhCurrentRuns(),completed=runs.filter(r=>r.status==='complete'),hall=rhRecordsMode==='hall';$('hall').innerHTML=`${hall?rhHeader('HALL OF FAME','Completed Championship winners','records','hall'):rhHeader('RECORDS','Your Racing History','records')}<div class="rhContent">${hall?rhHallOfFame(completed):`<button class="rhHallBanner" onclick="rhRecordsMode='hall';rhRenderRecords()"><span>🏆</span><b>HALL OF FAME</b><small>Completed Championship winners</small><em>›</em></button><section class="rhSection"><h2>Championship Records</h2>${runs.length?runs.slice().reverse().map(r=>`<details class="rhRecordRun"><summary><span><b>${esc(r.name)}</b><small>${r.status==='complete'?'Completed':'Active'} • ${r.results.length} results</small></span></summary>${r.rounds.map(rd=>{const best=r.results.filter(x=>x.roundId===rd.id).sort((a,b)=>a.time-b.time)[0];return `<div class="rhListRow"><span>${esc(rd.name)}</span><strong>${best?rhFmtTime(best.time):'—'}</strong></div>`}).join('')}</details>`).join(''):rhEmpty('NO RECORDS YET','Championship records will appear here after you start recording results.','View Championships',"show('festival')")}</section>`}</div>`}
function rhHallOfFame(completed){return `<section class="rhSection"><h2>Hall of Fame</h2>${completed.length?`<div class="rhHallGrid">${completed.map(r=>{const rows=r.entries.map(id=>{const rr=r.results.filter(x=>x.carId===id);return rr.length===r.rounds.length?{id,total:rr.reduce((a,b)=>a+b.time,0)}:null}).filter(Boolean).sort((a,b)=>a.total-b.total),w=rows[0];return `<div class="rhHallCard"><img src="${rhTrophy(r.trophy)}"><b>${esc(r.name)}</b><span>${w?esc(carName(carById(w.id))):'—'}</span><strong>${w?rhFmtTime(w.total):'—'}</strong></div>`}).join('')}</div>`:rhEmpty('HALL OF FAME IS EMPTY','Completed Championships will appear here with their trophy, winning car and final time.','View Championships',"show('festival')")}</section>`}
function rhRenderStats(){const s=rhSpace(),runs=s.runs||[],completed=runs.filter(r=>r.status==='complete'),results=runs.flatMap(r=>r.results||[]),time=results.reduce((a,b)=>a+Number(b.time||0),0);$('more').innerHTML=`${rhHeader('STATS','Your RaceHub at a glance','stats')}<div class="rhContent"><section class="rhStats"><div><span>Championships Created</span><b>${runs.length}</b></div><div class="primary"><span>Total Races</span><b>${results.length}</b></div><div><span>Championships Completed</span><b>${completed.length}</b></div><div class="odometer"><span>TIME DRIVEN</span><b>${rhDurationClock(time)}</b></div></section></div>`}
function rhDurationClock(v){const h=Math.floor(v/3600),m=Math.floor(v%3600/60),s=Math.floor(v%60);return [h,m,s].map(n=>String(n).padStart(2,'0')).join(':')}
function rhRenderSettings(){const s=rhSpace(),makes=rhMakeList();$('more').innerHTML=`<div class="rhScene rhSettingsScene">${rhHeader('SETTINGS','RaceHub Control Centre','settings')}</div><div class="rhContent"><section class="rhSection"><h2>Celebrations</h2>${['sound','confetti','vibrate'].map(k=>`<label class="rhToggle"><span>${k==='sound'?'Sounds':k==='confetti'?'Confetti':'Vibration'}</span><input type="checkbox" ${state.settings[k]?'checked':''} onchange="state.settings.${k}=this.checked;rhSave()"></label>`).join('')}</section><section class="rhSection"><h2>Garage / Profile</h2><label>Favourite Manufacturer</label><select onchange="rhChangeFavourite(this.value)"><option value="">Not set</option>${makes.map(m=>`<option ${m===s.favouriteManufacturer?'selected':''}>${esc(m)}</option>`).join('')}</select><p class="small">Changing Favourite Manufacturer removes the old Favourite Championship and any progress in its active run.</p></section><section class="rhSection"><h2>RaceHub Spaces</h2>${state.spaces.map(x=>`<button class="rhSpaceRow ${x.id===s.id?'active':''}" onclick="rhSwitchSpace('${x.id}')"><span><b>${esc(x.name)}</b><small>${x.cars.length} cars • ${(x.runs||[]).length} Championships</small></span><em>${x.id===s.id?'CURRENT':'›'}</em></button>`).join('')}<button class="btn secondary" onclick="rhCreateSpace()">CREATE NEW SPACE</button><p class="small">Play more than one racing game? Create a separate RaceHub for each one. Each RaceHub keeps its own Garage, Championships, Records, Hall of Fame and Stats separate.</p></section><section class="rhSection"><h2>Data</h2><button class="rhSettingRow" onclick="rhBackup()"><b>Backup</b><span>Create a RaceHub-managed backup ›</span></button><button class="rhSettingRow" onclick="rhRestoreList()"><b>Restore</b><span>Restore this Space from a saved backup ›</span></button></section><section class="rhSection danger"><h2>DANGER ZONE</h2><button class="btn dangerBtn" onclick="rhResetConfirm()">RESET RACING DATA</button><p class="small">Clears racing data for this Space while retaining its Garage, name, global Driver Profile and other Spaces.</p></section><section class="rhSection"><h2>About RaceHub</h2><h3>DRIVE • RECORD • IMPROVE</h3><p>RaceHub is your personal racing record book. Build your Garage, run Championships, record results and keep your racing history safe.</p><p class="small">Version ${RH_BUILD_VERSION} • Studio Final Build</p></section><button class="btn secondary" onclick="rhMoreMode='stats';rhRenderMore()">BACK TO STATS</button></div>`}
function rhChangeFavourite(v){const s=rhSpace(),old=s.favouriteManufacturer;if(old&&old!==v&&!confirm(`Change Favourite Manufacturer from ${old} to ${v||'Not set'}? Progress in the old Favourite Championship will be deleted.`)){rhRenderSettings();return}s.runs=s.runs.filter(r=>!(r.type==='favourite'&&r.value===old));s.favouriteManufacturer=v;rhSave();rhRenderSettings()}
function rhCreateSpace(){const name=prompt('RaceHub Name','');if(!name?.trim())return;const s=rhSpaceTemplate(name.trim(),[]);state.spaces.push(s);state.activeSpaceId=s.id;rhSync();rhSave();rhRenderSettings()}
function rhSwitchSpace(id){state.activeSpaceId=id;rhSync();rhSave();rhRenderSettings()}
function rhBackup(){const s=rhSpace(),b={id:rhId('backup'),spaceName:s.name,date:new Date().toISOString(),counts:{cars:s.cars.length,championships:s.runs.length,results:s.runs.flatMap(r=>r.results||[]).length},data:rhClone({cars:s.cars,favouriteManufacturer:s.favouriteManufacturer,runs:s.runs,customEvents:s.customEvents})};s.backups=s.backups||[];s.backups.push(b);rhSave();toast('Backup created');rhRenderSettings()}
function rhRestoreList(){const s=rhSpace(),bs=s.backups||[];document.body.insertAdjacentHTML('beforeend',`<div id="rhRestore" class="rhOverlay"><div class="rhModal"><button class="rhModalX" onclick="$('rhRestore').remove()">×</button><h2>Restore Backup</h2>${bs.length?bs.slice().reverse().map(b=>`<button class="rhSpaceRow" onclick="rhRestore('${b.id}')"><span><b>${esc(b.spaceName)}</b><small>${new Date(b.date).toLocaleString('en-GB')} • ${b.counts.cars} cars • ${b.counts.championships} Championships</small></span><em>›</em></button>`).join(''):rhEmpty('NO SAVED BACKUPS','Create a backup before making major changes.','Create Backup',"$('rhRestore').remove();rhBackup()")}</div></div>`)}
function rhRestore(id){const s=rhSpace(),b=(s.backups||[]).find(x=>x.id===id);if(!b)return;if(!confirm('Restore this backup? It will replace the current Space only and cannot be undone. Other Spaces are unaffected.'))return;Object.assign(s,rhClone(b.data));s.backups=s.backups||[];rhSync();rhSave();$('rhRestore')?.remove();rhRenderSettings()}
function rhResetConfirm(){if(!confirm('Reset Racing Data? This clears Championships, results, Records, Hall of Fame, Stats and Favourite Manufacturer for the current Space. Your Garage, Space name, global Driver Profile and other Spaces are retained.'))return;const s=rhSpace();s.runs=[];s.customEvents=[];s.favouriteManufacturer='';rhSave();toast('Racing data reset');rhRenderSettings()}
function rhRenderMore(){rhMoreMode==='settings'?rhRenderSettings():rhRenderStats()}
function rhRender(screen){if(screen==='home')rhRenderHome();else if(screen==='festival')rhRenderFestival();else if(screen==='events')rhRenderEvents();else if(screen==='garage')rhRenderGarage();else if(screen==='hall')rhRenderRecords();else if(screen==='more')rhRenderMore();}
// Override legacy edit save so it writes the active Space.
const rhLegacyEditCar=editCar;
editCar=function(id){rhLegacyEditCar(id)};
const rhLegacySaveCarEdit=saveCarEdit;
saveCarEdit=function(id){rhLegacySaveCarEdit(id);rhSpace().cars=state.cars;rhSave();if(currentScreen==='garage')rhRenderGarage()};
load=rhLoad;render=rhRender;
